# HTTP 代理端口
# port: 7890
# SOCKS5 代理端口
# socks-port: 7891
# HTTP&SOCKS5 混合端口
mixed-port: 7893

# 允许局域网的连接（可用来共享代理）
allow-lan: true

bind-address: "*"

# 本地 SOCKS5 / HTTP(S) 服务认证
authentication:
  - "admin:901203"
  - "admin:901203"


# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

 # 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
 # 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# 外部管理IP和端口
external-controller: 0.0.0.0:9090
# 外部管理密码
# secret: '123456'


dns:
  enable: false
  # When set to false, resolver won't translate hostnames to IPv6 addresses
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip # 或 redir-host
  fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  use-hosts: true

  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  fallback: # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853

  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - name: 🇫🇷法国SSR
    server: fr-am1-5.eqsunshine.com
    port: 8181
    type: ssr
    cipher: aes-256-cfb
    password: RcfVcDzzB
    protocol: origin
    obfs: tls1.2_ticket_auth
    protocol-param: ""
    obfs-param: ""
  - name: "🇺🇸美國專線 : 洛杉磯10G 443"
    type: http
    server: c9e42a84-rujz40-rzdfln-7q16.on1t.com
    port: "443"
    tls: true
    _index: 18
  - name: 🇺🇸美國 80
    type: vmess
    server: 192.203.230.86
    port: "80"
    uuid: a442dacf-cbb3-488a-9744-61494ea38630
    alterId: "0"
    cipher: auto
    network: ws
    ws-opts:
      path: /
      headers:
        Host: us-1.acyun.cf
  - name: "🇺🇸美國西岸 : 洛杉磯2 443"
    type: http
    server: a9855dd9-rujz40-rzdfln-7q16.copydesign.net
    port: "443"
    tls: true
  - name: " ChatGPT测试：443"
    type: http
    server: 7f50ac06-rujz40-rzdfln-7q16.uk.n7ai.com
    port: "443"
    tls: true
  - name: 测试 1044
    type: http
    server: e50eda89-rujz40-rzdfln-7q16.uk.z7zi.com
    port: "1044"
    tls: true
  - name: "🇭🇰香港商寬2 : 香港HKBN 1120"
    type: http
    server: 172fa2f6-rujz40-rzdfln-7q16.chromeapi.net
    port: "1120"
    tls: true
  - name: "🇭🇰香港商寬 : 香港HKT 2128"
    type: http
    server: dbca5c79-rujz40-rzdfln-7q16.alrihla.net
    port: "2128"
    tls: true
    _index: 3
  - name: "🇹🇼中國台灣 : 台北 2330"
    type: http
    server: 172fa2f6-rujz40-rzdfln-7q16.chromeapi.net
    port: "2330"
    tls: true
    _index: 3
  - name: "🇸🇬新加坡 : 新加坡 2400"
    type: http
    server: 3971e28d-rujz40-rzdfln-7q16.j2ai.com
    port: "2400"
    tls: true
  - name: "🇺🇸美國加州 : 洛杉磯 3310"
    type: http
    server: 3971e28d-rujz40-rzdfln-7q16.j2ai.com
    port: "3310"
    tls: true
  - name: "🇭🇰香港精品 : 香港10G 5228"
    type: http
    server: d769ce3a-rujz40-rzdfln-7q16.sphinxsearch.net
    port: "5228"
    tls: true
  - name: 🇩🇪德國 443
    type: http
    server: abd67862-rug9s0-7q16.de.p5pv.com
    port: "443"
    username: eb13980206608@gmail.com
    password: e9ed3e80-e954-11ed-8d3b-f23c91369f2d
    tls: true
proxy-groups:
  - name: Ghelper
    proxies:
      - 全球智能
      - 🇩🇪德國 443
      - 🇺🇸美國 80
      - 🇫🇷法国SSR
      - " ChatGPT测试：443"
      - "🇺🇸美國專線 : 洛杉磯10G 443"
      - "🇺🇸美國西岸 : 洛杉磯2 443"
      - 测试 1044
      - "🇭🇰香港商寬2 : 香港HKBN 1120"
      - "🇭🇰香港商寬 : 香港HKT 2128"
      - "🇹🇼中國台灣 : 台北 2330"
      - "🇸🇬新加坡 : 新加坡 2400"
      - "🇺🇸美國加州 : 洛杉磯 3310"
      - "🇭🇰香港精品 : 香港10G 5228"
    type: select
  - interval: 3600
    name: 全球智能
    proxies:
      - 🇺🇸美國 80
      - " ChatGPT测试：443"
      - 🇫🇷法国SSR
      - "🇺🇸美國專線 : 洛杉磯10G 443"
      - 测试 1044
      - "🇸🇬新加坡 : 新加坡 2400"
      - "🇭🇰香港商寬 : 香港HKT 2128"
      - "🇹🇼中國台灣 : 台北 2330"
      - "🇺🇸美國加州 : 洛杉磯 3310"
      - "🇺🇸美國西岸 : 洛杉磯2 443"
      - "🇭🇰香港精品 : 香港10G 5228"
      - 🇩🇪德國 443
      - "🇭🇰香港商寬2 : 香港HKBN 1120"
    type: url-test
    url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN-SUFFIX,ip-api.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,myds.me,DIRECT
  - DOMAIN-SUFFIX,ip138.com,DIRECT
  - DOMAIN-SUFFIX,stunnel.vip,DIRECT
  - DOMAIN-SUFFIX,gotochinatown.net,DIRECT
  - DOMAIN-SUFFIX,ghelper.net,DIRECT
  - DOMAIN-SUFFIX,ghelper.me,DIRECT
  - DOMAIN-SUFFIX,ghelper.xyz,DIRECT
  - DOMAIN-SUFFIX,ghelper.org,DIRECT
  - DOMAIN-SUFFIX,fastapi.me,DIRECT
  - DOMAIN-SUFFIX,vps315.com,DIRECT
  - DOMAIN-SUFFIX,copyplay.net,DIRECT
  - DOMAIN-SUFFIX,pickdown.net,DIRECT
  - DOMAIN-KEYWORD,google,Ghelper
  - DOMAIN-KEYWORD,youtube,Ghelper
  - DOMAIN-SUFFIX,ggpht.com,Ghelper
  - DOMAIN-SUFFIX,gmail.com,Ghelper
  - DOMAIN-SUFFIX,gvt2.com,Ghelper
  - DOMAIN-SUFFIX,gvt3.com,Ghelper
  - DOMAIN-SUFFIX,chrome.com,Ghelper
  - DOMAIN-SUFFIX,wikipedia.org,Ghelper
  - DOMAIN-SUFFIX,wikimedia.org,Ghelper
  - DOMAIN-SUFFIX,appspot.com,Ghelper
  - DOMAIN-SUFFIX,android.com,Ghelper
  - DOMAIN-SUFFIX,github.com,Ghelper
  - DOMAIN-SUFFIX,gitbook.com,Ghelper
  - DOMAIN-SUFFIX,kaggle.com,Ghelper
  - DOMAIN-SUFFIX,arxiv.org,Ghelper
  - DOMAIN-SUFFIX,wiktionary.org,Ghelper
  - DOMAIN-SUFFIX,blogger.com,Ghelper
  - DOMAIN-SUFFIX,youtu.be,Ghelper
  - DOMAIN-SUFFIX,ytimg.com,Ghelper
  - DOMAIN-SUFFIX,youtube.com,Ghelper
  - DOMAIN-SUFFIX,instagram.com,Ghelper
  - DOMAIN-SUFFIX,twitter.com,Ghelper
  - DOMAIN-SUFFIX,t.co,Ghelper
  - DOMAIN-SUFFIX,facebook.com,Ghelper
  - DOMAIN-SUFFIX,telegram.org,Ghelper
  - DOMAIN-SUFFIX,pikpak.com,Ghelper
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,172.23.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,fd00::/8,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Ghelper
