mixed-port: 7893
allow-lan: true
bind-address: "*"
authentication:
  - admin:901203
  - admin:901203
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: false
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - name: "🇺🇸美國專線 : 洛杉磯10G 443"
    type: http
    server: 9d01ec3c-rvu9s0-rzdfln-7q16.on1t.com
    port: "443"
    tls: true
  - name: "🇺🇸美國西岸 : 洛杉磯2 443"
    type: http
    server: f1ced31f-rvu9s0-rzdfln-7q16.copydesign.net
    port: "443"
    tls: true
  - name: "🇭🇰香港商寬2 : 香港HKBN 1120"
    type: http
    server: ecfd4546-rvu9s0-rzdfln-7q16.chromeapi.net
    port: "1120"
    tls: true
  - name: "🇭🇰香港商寬 : 香港HKT 2128"
    type: http
    server: 752ddee0-rvu9s0-rzdfln-7q16.alrihla.net
    port: "2128"
    tls: true
  - name: "🇹🇼中國台灣 : 台北 2330"
    type: http
    server: ecfd4546-rvu9s0-rzdfln-7q16.chromeapi.net
    port: "2330"
    tls: true
  - name: "🇭🇰香港精品 : 香港10G 5228"
    type: http
    server: 095d64a0-rvu9s0-rzdfln-7q16.sphinxsearch.net
    port: "5228"
    tls: true
  - name: 🇩🇪德國 443
    type: http
    server: 505f6270-ruysg0-7q16.de.p5pv.com
    port: "443"
    username: eb13980206608@gmail.com
    password: e9ed3e80-e954-11ed-8d3b-f23c91369f2d
    tls: true
proxy-groups:
  - name: Ghelper
    proxies:
      - 全球智能
      - 🇩🇪德國 443
      - "🇺🇸美國專線 : 洛杉磯10G 443"
      - "🇺🇸美國西岸 : 洛杉磯2 443"
      - "🇭🇰香港商寬2 : 香港HKBN 1120"
      - "🇭🇰香港商寬 : 香港HKT 2128"
      - "🇹🇼中國台灣 : 台北 2330"
      - "🇭🇰香港精品 : 香港10G 5228"
    type: select
  - interval: 3600
    name: 全球智能
    proxies:
      - "🇺🇸美國專線 : 洛杉磯10G 443"
      - "🇭🇰香港商寬 : 香港HKT 2128"
      - "🇹🇼中國台灣 : 台北 2330"
      - "🇺🇸美國西岸 : 洛杉磯2 443"
      - "🇭🇰香港精品 : 香港10G 5228"
      - 🇩🇪德國 443
      - "🇭🇰香港商寬2 : 香港HKBN 1120"
    type: url-test
    url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN-SUFFIX,ip-api.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,myds.me,DIRECT
  - DOMAIN-SUFFIX,ip138.com,DIRECT
  - DOMAIN-SUFFIX,stunnel.vip,DIRECT
  - DOMAIN-SUFFIX,gotochinatown.net,DIRECT
  - DOMAIN-SUFFIX,ghelper.net,DIRECT
  - DOMAIN-SUFFIX,ghelper.me,DIRECT
  - DOMAIN-SUFFIX,ghelper.xyz,DIRECT
  - DOMAIN-SUFFIX,ghelper.org,DIRECT
  - DOMAIN-SUFFIX,fastapi.me,DIRECT
  - DOMAIN-SUFFIX,vps315.com,DIRECT
  - DOMAIN-SUFFIX,copyplay.net,DIRECT
  - DOMAIN-SUFFIX,pickdown.net,DIRECT
  - DOMAIN-KEYWORD,google,Ghelper
  - DOMAIN-KEYWORD,youtube,Ghelper
  - DOMAIN-SUFFIX,ggpht.com,Ghelper
  - DOMAIN-SUFFIX,gmail.com,Ghelper
  - DOMAIN-SUFFIX,gvt2.com,Ghelper
  - DOMAIN-SUFFIX,gvt3.com,Ghelper
  - DOMAIN-SUFFIX,chrome.com,Ghelper
  - DOMAIN-SUFFIX,wikipedia.org,Ghelper
  - DOMAIN-SUFFIX,wikimedia.org,Ghelper
  - DOMAIN-SUFFIX,appspot.com,Ghelper
  - DOMAIN-SUFFIX,android.com,Ghelper
  - DOMAIN-SUFFIX,github.com,Ghelper
  - DOMAIN-SUFFIX,gitbook.com,Ghelper
  - DOMAIN-SUFFIX,kaggle.com,Ghelper
  - DOMAIN-SUFFIX,arxiv.org,Ghelper
  - DOMAIN-SUFFIX,wiktionary.org,Ghelper
  - DOMAIN-SUFFIX,blogger.com,Ghelper
  - DOMAIN-SUFFIX,youtu.be,Ghelper
  - DOMAIN-SUFFIX,ytimg.com,Ghelper
  - DOMAIN-SUFFIX,youtube.com,Ghelper
  - DOMAIN-SUFFIX,instagram.com,Ghelper
  - DOMAIN-SUFFIX,twitter.com,Ghelper
  - DOMAIN-SUFFIX,t.co,Ghelper
  - DOMAIN-SUFFIX,facebook.com,Ghelper
  - DOMAIN-SUFFIX,telegram.org,Ghelper
  - DOMAIN-SUFFIX,pikpak.com,Ghelper
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,172.23.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,fd00::/8,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Ghelper
